// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRimzSrt88w4VnxCwYPjDHU1vOjdXnKs0',
    appId: '1:165200747868:android:996e304d3a6ffdd8dd3599',
    messagingSenderId: '165200747868',
    projectId: 'skyvo-7ee8e',
    storageBucket: 'skyvo-7ee8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkj_9l-IR9C92GpaeDVV9O3af_cLcWY9k',
    appId: '1:165200747868:ios:72bd7a4a46ca91bedd3599',
    messagingSenderId: '165200747868',
    projectId: 'skyvo-7ee8e',
    storageBucket: 'skyvo-7ee8e.appspot.com',
    androidClientId: '165200747868-sj0rq7rp8rf179b6d4se8ngm6s56b9n9.apps.googleusercontent.com',
    iosClientId: '165200747868-pg89ubt3vcgf68hssbarc6dh0s4d7ffd.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentitUser',
  );

}