class CarModel {
  final String id;
  final String brandId;
  final String model;
  final String color;
  final double condition;
  final int seats;
  final String fuelType;
  final String transmission;
  final bool airConditioning;
  final double speed;
  final List<String> imageUrls;
  final String description;
  final double pricePerDay;
  final bool isBooked;
  final DateTime createdAt;
  final DateTime updatedAt;

  CarModel({
    required this.id,
    required this.brandId,
    required this.model,
    required this.color,
    required this.condition,
    required this.seats,
    required this.fuelType,
    required this.transmission,
    required this.airConditioning,
    required this.speed,
    required this.imageUrls,
    required this.description,
    required this.pricePerDay,
    required this.isBooked,
    required this.createdAt,
    required this.updatedAt,
  });

  factory CarModel.fromJson(Map<String, dynamic> json) {
    return CarModel(
      id: json['id'],
      brandId: json['brandId'],
      model: json['model'],
      color: json['color'],
      condition: json['condition'].toDouble(),
      seats: json['seats'],
      fuelType: json['fuelType'],
      transmission: json['transmission'],
      airConditioning: json['airConditioning'],
      speed: json['speed']?.toDouble() ?? 0.0,
      imageUrls: List<String>.from(json['imageUrls']),
      description: json['description'],
      pricePerDay: json['pricePerDay'].toDouble(),
      isBooked: json['isBooked'],
      createdAt: DateTime.parse(json['createdAt']),
      updatedAt: DateTime.parse(json['updatedAt']),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'brandId': brandId,
      'model': model,
      'color': color,
      'condition': condition,
      'seats': seats,
      'fuelType': fuelType,
      'transmission': transmission,
      'speed': speed,
      'airConditioning': airConditioning,
      'imageUrls': imageUrls,
      'description': description,
      'pricePerDay': pricePerDay,
      'isBooked': isBooked,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
    };
  }

  CarModel copyWith({
    String? id,
    String? brandId,
    String? model,
    String? color,
    double? condition,
    int? seats,
    String? fuelType,
    String? transmission,
    bool? airConditioning,
    double? speed,
    List<String>? imageUrls,
    String? description,
    double? pricePerDay,
    bool? isBooked,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return CarModel(
      id: id ?? this.id,
      brandId: brandId ?? this.brandId,
      model: model ?? this.model,
      color: color ?? this.color,
      condition: condition ?? this.condition,
      seats: seats ?? this.seats,
      fuelType: fuelType ?? this.fuelType,
      transmission: transmission ?? this.transmission,
      airConditioning: airConditioning ?? this.airConditioning,
      speed: speed ?? this.speed,
      imageUrls: imageUrls ?? this.imageUrls,
      description: description ?? this.description,
      pricePerDay: pricePerDay ?? this.pricePerDay,
      isBooked: isBooked ?? this.isBooked,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}

List<CarModel> dummyCarsList = [
  CarModel(
    id: '1',
    brandId: '1',
    model: 'Model S',
    color: 'Red',
    condition: 9.5,
    seats: 5,
    fuelType: 'Electric',
    speed: 250.0,
    transmission: 'A',
    airConditioning: true,
    imageUrls: [
      'https://img.freepik.com/premium-vector/realistic-black-sport-two-tone-luxury-car-set-grey-metallic-background-vector_33869-3703.jpg?semt=ais_hybrid&w=740',
    ],
    description: 'A premium electric sedan.',
    pricePerDay: 150.0,
    isBooked: false,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CarModel(
    id: '2',
    brandId: '2',
    model: 'Civic',
    color: 'Blue',
    condition: 8.0,
    seats: 5,
    fuelType: 'Petrol',
    speed: 180.0,
    transmission: 'M',
    airConditioning: true,
    imageUrls: [
      'https://img.freepik.com/free-psd/modern-car-isolated_23-2151504578.jpg?semt=ais_hybrid&w=740',
    ],
    description: 'A reliable compact car.',
    pricePerDay: 50.0,
    isBooked: false,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CarModel(
    id: '3',
    brandId: '3',
    model: 'Corolla',
    color: 'White',
    condition: 8.5,
    seats: 5,
    fuelType: 'Hybrid',
    speed: 190.0,
    transmission: 'A',
    airConditioning: true,
    imageUrls: [
      'https://img.freepik.com/premium-photo/black-premium-city-crossover-white-background-3d-rendering_101266-929.jpg?semt=ais_hybrid&w=740',
    ],
    description: 'A fuel-efficient sedan.',
    pricePerDay: 60.0,
    isBooked: false,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CarModel(
    id: '4',
    brandId: '4',
    model: 'Mustang',
    color: 'Black',
    condition: 9.0,
    seats: 4,
    fuelType: 'Petrol',
    speed: 300.0,
    transmission: 'A',
    airConditioning: true,
    imageUrls: [
      'https://img.freepik.com/free-photo/3d-car-with-simple-background_23-2150796882.jpg?semt=ais_hybrid&w=740',
    ],
    description: 'A powerful sports car.',
    pricePerDay: 200.0,
    isBooked: false,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CarModel(
    id: '5',
    brandId: '5',
    model: 'X5',
    color: 'Silver',
    condition: 9.2,
    seats: 7,
    fuelType: 'Diesel',
    speed: 220.0,
    transmission: 'A',
    airConditioning: true,
    imageUrls: [
      'https://img.freepik.com/free-vector/black-hatchback-car-isolated-white-vector_53876-67410.jpg?semt=ais_hybrid&w=740',
    ],
    description: 'A luxury SUV.',
    pricePerDay: 180.0,
    isBooked: false,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CarModel(
    id: '6',
    brandId: '6',
    model: 'A4',
    color: 'Grey',
    condition: 8.8,
    seats: 5,
    fuelType: 'Petrol',
    speed: 210.0,
    transmission: 'A',
    airConditioning: true,
    imageUrls: [
      'https://img.freepik.com/free-psd/modern-car-isolated_23-2151504578.jpg?semt=ais_hybrid&w=740',
    ],
    description: 'A stylish sedan.',
    pricePerDay: 120.0,
    isBooked: true,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CarModel(
    id: '7',
    brandId: '1',
    model: 'Model X',
    color: 'White',
    condition: 9.7,
    seats: 7,
    fuelType: 'Electric',
    speed: 240.0,
    transmission: 'A',
    airConditioning: true,
    imageUrls: [
      'https://img.freepik.com/premium-vector/realistic-black-sport-two-tone-luxury-car-set-grey-metallic-background-vector_33869-3703.jpg?semt=ais_hybrid&w=740',
    ],
    description: 'A premium electric SUV.',
    pricePerDay: 200.0,
    isBooked: false,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CarModel(
    id: '8',
    brandId: '2',
    model: 'Accord',
    color: 'Black',
    condition: 8.3,
    seats: 5,
    fuelType: 'Hybrid',
    speed: 200.0,
    transmission: 'A',
    airConditioning: true,
    imageUrls: [
      'https://img.freepik.com/free-psd/modern-car-isolated_23-2151504578.jpg?semt=ais_hybrid&w=740',
    ],
    description: 'A spacious and efficient sedan.',
    pricePerDay: 70.0,
    isBooked: false,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CarModel(
    id: '9',
    brandId: '3',
    model: 'Camry',
    color: 'Blue',
    condition: 8.9,
    seats: 5,
    fuelType: 'Hybrid',
    speed: 210.0,
    transmission: 'A',
    airConditioning: true,
    imageUrls: [
      'https://img.freepik.com/free-photo/3d-car-with-simple-background_23-2150796882.jpg?semt=ais_hybrid&w=740',
    ],
    description: 'A comfortable and reliable sedan.',
    pricePerDay: 75.0,
    isBooked: true,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CarModel(
    id: '10',
    brandId: '4',
    model: 'Explorer',
    color: 'Red',
    condition: 9.1,
    seats: 7,
    fuelType: 'Petrol',
    speed: 230.0,
    transmission: 'A',
    airConditioning: true,
    imageUrls: [
      'https://img.freepik.com/premium-vector/realistic-black-sport-two-tone-luxury-car-set-grey-metallic-background-vector_33869-3703.jpg?semt=ais_hybrid&w=740',
    ],
    description: 'A versatile SUV.',
    pricePerDay: 150.0,
    isBooked: true,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
